### ISSUE TITLE
サイト内で投票機能を実装する

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/2024-quaint-app#58]
昨年度のリベンジ

https://github.com/hibiya-itchief/2023-quaint-app/issues/500

**Comment by aozoraUS** [comment]
この機能は去年はどのようなイメージで実装しようということになったんですか？投票機能ならチーフがmicrosoftのformsとかでやった方が混乱もないし使い勝手がいいように感じるのですが

**Comment by hibiyahibiyahibiya** [comment]
投票機能をseiryofes.com上で実装する、っていうことで、/ticketsからたぶん/votesに飛ぶ感じかな？

自クラスに投票できないようにする、っていうのが可能っていうのが一応自前実装のメリットの一つだけど、
確かに変に自分で作ろうとせず既にあるサービスを利用していこうの姿勢は良いかも
discordの方でちゃんと議論がしたいかも

**Comment by ekkekuru2** [comment]
当初、「整理券を取って実際に観劇したクラスにしか投票できない」という制約をつけたいという要望があったと記憶してる。コロナ禍以前は紙の整理券をそのまま箱に入れて投票してたから、オンライン化しても整理券=投票券にしよう、と。
もちろん今年のチーフ会の人がどう考えるか次第だけど。

劇を作るクラ代目線では確かに、実際に内容を見てくれた人に決めて欲しいと思う。個人的な意見だけど

あと実装という面で言うと、整理券を取ったか(=ticketsテーブルに、そのuser_idかつgroup_idの行が存在するか)、という簡単な判定方法で、(新しくフィールドを追加したりテーブルを増やしたりせずに)自動的に1人複数回投票とか自クラスへの投票が抑止できるなーと当時の俺は考えてた。

**Comment by aozoraUS** [comment]
APIの方は完成ずみ
