### ISSUE TITLE
タグ機能を拡張する

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/2024-quaint-app#7]
'23では、１年生・２年生・３年生はクラス劇のことを指し、
Hebe他のタグとは重複しえない
つまり、タグ=団体の種類だった
ただ、「１年生」だけ見たら確かに１年生が参加している団体(e.g.１年生バンド)のことを指していそうと捉えるよなーと。

また今、Hebe、外部団体、部活動、のいずれかのタグを持っていると整理券一覧を表示させないようにしているのですが、フロント側でそういうタグが存在することを前提にしてしまっているのもよくないかも。

また、Hebe等に何年生が出るかという情報もあった方がうれしいだろうから、クラス劇のタグとどう住み分けるか検討が必要。

APIの変更を伴うかどうかも含めて議論が必要かな……

メモ…「整理券を取得できる団体かどうか」という項目を持たせるという案。APIの変更になる。

https://github.com/hibiya-itchief/quaint-app/issues/393
https://github.com/hibiya-itchief/quaint-app/issues/351

**Comment by aozoraUS** [comment]
話を本格的に進めましょう。Discordでスレッド立てます

**Comment by aozoraUS** [comment]
このissueってもう他にやることなさそうですか？

**Comment by hibiyahibiyahibiya** [comment]
今度は、タグの表示上の扱いをどうしようっていう話があるかもね
あとtypeで表示絞れるようにしたいとか
