### ISSUE TITLE
/_groupId 場所の案内

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/2024-quaint-app#83]
![327118112-1018f1a1-8682-4bd5-8f8d-abba1b8c4bf2](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/381d3130-0711-45fa-a3f3-1cb7672b75dd)
(去年の五月祭のサイトより)

いま新しくできたfloor, placeプロパティを/groupIdでも生かそう

https://github.com/hibiya-itchief/2023-quaint-app/issues/351

**Comment by aozoraUS** [comment]
これやりますね
