### ISSUE TITLE
デザインかをよくする

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/2024-quaint-app#88]
Vuetifyの典型的なマテリアルデザイン、開発者勢からは不評
いい感じのデザインを目指そう

あと、Webアプリとして、"アプリらしさ"がもっと欲しい！！

**Comment by aozoraUS** [comment]
Vuetifyってマテリアルデザインの設計に厳密に従うように作成されたUIフレームワークですよ。タイトル変えません？デザインをよくするとかに

**Comment by hibiyahibiyahibiya** [comment]
でもこれ、ちゃんとデザインのやり方が確立されたらもう消していいissueな気はする

**Comment by aozoraUS** [comment]
それはそうですよね。それぞれ個別にデザインの修正のissueが立っていくと思います
