### ISSUE TITLE
一般の方のログイン方法

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/2024-quaint-app#91]
とりあえず、チーフ会の整理券担当の人との会話などでは、
「QRコード = アカウント」
という単純化を行っている

けど、実際QRコードを読み込んだらログインできる、ってなんだ…？？
url,json,・・・

一般の方用のアカウントを作成して、それを来場した一般の方に割り振る、という形なことは決まっている

**Comment by aozoraUS** [comment]
現状：entra ID でアカウント作成して、そのユーザー名とパスワードを配る

**Comment by aozoraUS** [comment]
機能は作り終わっているはず。また何か問題が起きたらissue建て直します
